export const EVENT_TYPES = [
  'DEBATE_CREATED',
  'ROUND_CREATED',
  'AGENT_REGISTERED',
  'MESSAGE_CREATED',
  'MESSAGE_DISPATCHED',
  'DELIVERY_CREATED',
  'DELIVERY_CONFIRMED',
  'RESPONSE_CAPTURED',
  'EXPOSURE_CREATED',
  'ROUND_COMPLETED',
  'SYNTHESIS_CREATED',
  'OPERATOR_INTERVENTION',
] as const;

export type EventType = (typeof EVENT_TYPES)[number];
