import type { DebateWorkspaceView } from './types.js';

/** Static UX mock for Checkpoint 1 — not live runtime data. */
export const MOCK_DEBATE_VIEW: DebateWorkspaceView = {
  title: 'Should Rayzan use SQLite or PostgreSQL?',
  subtitle: "Evaluating the best database for Rayzan's current and future needs.",
  badge: 'In Progress',
  stages: [
    {
      id: 'reframe',
      label: 'Reframe',
      detail: 'Clarify the question',
      status: 'completed',
    },
    {
      id: 'round1',
      label: 'Round 1',
      detail: 'Initial perspectives',
      status: 'completed',
    },
    {
      id: 'challenge',
      label: 'Challenge',
      detail: 'Deepen the analysis',
      status: 'active',
    },
    {
      id: 'synthesis',
      label: 'Synthesis',
      detail: 'Integrate insights',
      status: 'waiting',
    },
    {
      id: 'decision',
      label: 'Decision',
      detail: 'Final recommendation',
      status: 'waiting',
    },
  ],
  details: [
    { label: 'Coordinator framing', status: 'completed' },
    { label: 'Round 1 analysis', status: 'completed' },
    { label: 'Round 2 challenge', status: 'active' },
    { label: 'Watcher responses', status: 'completed', note: '2 of 2 received' },
  ],
  nextAction: 'Coordinator synthesis · Estimated in 2–3 minutes',
  agents: [
    {
      id: 'deepseek',
      name: 'DeepSeek',
      role: 'coordinator',
      provider: 'DeepSeek',
      status: 'Waiting',
      summary: 'Waiting for Round 2 Watcher responses',
      phasesDone: 3,
      phasesTotal: 5,
    },
    {
      id: 'qwen',
      name: 'Qwen',
      role: 'watcher',
      provider: 'Qwen',
      status: 'Responded',
      summary: 'Round 2 response received / Analyzing position',
      phasesDone: 3,
      phasesTotal: 5,
      round1: 'Completed',
      round2: 'Completed',
    },
    {
      id: 'glm',
      name: 'GLM',
      role: 'watcher',
      provider: 'GLM',
      status: 'Responded',
      summary: 'Round 2 response received / Analyzing position',
      phasesDone: 3,
      phasesTotal: 5,
      round1: 'Completed',
      round2: 'Completed',
    },
  ],
  timeline: [
    {
      id: '1',
      title: 'Coordinator reframed the problem',
      detail: 'DeepSeek clarified the database choice for Rayzan.',
      time: '10:12 AM',
      status: 'completed',
    },
    {
      id: '2',
      title: 'Qwen submitted Round 1 analysis',
      detail: 'Independent perspective captured.',
      time: '10:14 AM',
      status: 'completed',
    },
    {
      id: '3',
      title: 'GLM submitted Round 1 analysis',
      detail: 'Independent perspective captured.',
      time: '10:15 AM',
      status: 'completed',
    },
    {
      id: '4',
      title: 'Coordinator issued Round 2 challenges',
      detail: 'Personalized challenges sent to Watchers.',
      time: '10:17 AM',
      status: 'completed',
    },
    {
      id: '5',
      title: 'Coordinator reviewing responses',
      detail: 'Preparing synthesis from Round 2 evidence.',
      time: 'In progress',
      status: 'active',
    },
  ],
  insights: {
    agreement: [],
    disagreement: [],
    risks: [],
  },
  transcript: [
    {
      id: 't1',
      from: 'Operator',
      kind: 'input',
      body: 'Should Rayzan use SQLite or PostgreSQL?',
    },
    {
      id: 't2',
      from: 'DeepSeek',
      kind: 'brief',
      body: 'Rephrased problem and independent Round 1 roles for Watchers.',
    },
  ],
};
